name: Build and Push Container Images

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: git.shadyknollcave.io
  REGISTRY_USER: micro
  TINYBIRD_IMAGE: git.shadyknollcave.io/micro/tinybird-local
  ANALYTICS_IMAGE: git.shadyknollcave.io/micro/traffic-analytics

jobs:
  build-traffic-analytics:
    name: Build Traffic Analytics
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git curl podman

      - name: Checkout repository
        run: |
          git clone https://git.shadyknollcave.io/micro/tinybird.git /workspace/tinybird
          cd /workspace/tinybird
          git checkout ${{ github.sha }}

      - name: Clone Traffic Analytics repository
        run: |
          git clone --depth 1 https://github.com/TryGhost/TrafficAnalytics.git /workspace/traffic-analytics-src
          cd /workspace/traffic-analytics-src
          TRAFFIC_COMMIT=$(git rev-parse --short HEAD)
          echo "TRAFFIC_COMMIT=${TRAFFIC_COMMIT}" >> $GITHUB_ENV

      - name: Verify Podman
        run: |
          podman version
          podman info

      - name: Log in to Gitea Container Registry
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin

      - name: Extract metadata (tags)
        id: meta
        run: |
          TAGS=""

          # Add branch-based tags
          if [ "${{ github.ref_type }}" == "branch" ]; then
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/-/g')
            TAGS="$TAGS ${{ env.ANALYTICS_IMAGE }}:${BRANCH_NAME}"

            # Add SHA tag
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            TAGS="$TAGS ${{ env.ANALYTICS_IMAGE }}:${BRANCH_NAME}-${SHORT_SHA}"

            # Add latest tag for main branch
            if [ "${{ github.ref_name }}" == "main" ]; then
              TAGS="$TAGS ${{ env.ANALYTICS_IMAGE }}:latest"
            fi
          fi

          # Add version tags for releases
          if [ "${{ github.ref_type }}" == "tag" ]; then
            VERSION="${{ github.ref_name }}"
            TAGS="$TAGS ${{ env.ANALYTICS_IMAGE }}:${VERSION}"

            # Add semver tags
            if [[ $VERSION =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
              MAJOR="${BASH_REMATCH[1]}"
              MINOR="${BASH_REMATCH[2]}"
              TAGS="$TAGS ${{ env.ANALYTICS_IMAGE }}:${MAJOR}"
              TAGS="$TAGS ${{ env.ANALYTICS_IMAGE }}:${MAJOR}.${MINOR}"
            fi
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "Generated tags: $TAGS"

      - name: Build Traffic Analytics
        run: |
          cd /workspace/traffic-analytics-src

          # Build with podman
          podman build \
            --platform linux/amd64 \
            --label "org.opencontainers.image.source=https://github.com/TryGhost/TrafficAnalytics" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            -t ${{ env.ANALYTICS_IMAGE }}:build \
            .

      - name: Push Traffic Analytics
        run: |
          for TAG in ${{ steps.meta.outputs.tags }}; do
            echo "Tagging and pushing: $TAG"
            podman tag ${{ env.ANALYTICS_IMAGE }}:build $TAG
            podman push $TAG
          done

          echo "Successfully pushed all tags"

  mirror-tinybird:
    name: Mirror Tinybird Local
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y podman

      - name: Verify Podman
        run: podman version

      - name: Log in to Gitea Container Registry
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin

      - name: Pull and mirror Tinybird Local
        run: |
          # Pull upstream image
          podman pull --platform linux/amd64 docker.io/tinybirdco/tinybird-local:latest

          # Tag for our registry
          podman tag docker.io/tinybirdco/tinybird-local:latest ${{ env.TINYBIRD_IMAGE }}:latest

          # Tag with date
          DATE_TAG=$(date +%Y%m%d)
          podman tag docker.io/tinybirdco/tinybird-local:latest ${{ env.TINYBIRD_IMAGE }}:${DATE_TAG}

          # Push all tags
          podman push ${{ env.TINYBIRD_IMAGE }}:latest
          podman push ${{ env.TINYBIRD_IMAGE }}:${DATE_TAG}

          # Tag with version if this is a release
          if [ "${{ github.ref_type }}" == "tag" ]; then
            VERSION="${{ github.ref_name }}"
            podman tag docker.io/tinybirdco/tinybird-local:latest ${{ env.TINYBIRD_IMAGE }}:${VERSION}
            podman push ${{ env.TINYBIRD_IMAGE }}:${VERSION}
          fi

      - name: Verify images
        run: |
          echo "Images pushed successfully:"
          podman images | grep tinybird-local || echo "No local images (expected after push)"

  update-manifests:
    name: Update Kubernetes Manifests
    runs-on: ubuntu-latest
    needs: [build-traffic-analytics, mirror-tinybird]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git

      - name: Configure Git
        run: |
          git config --global user.name "gitea-actions[bot]"
          git config --global user.email "gitea-actions[bot]@git.shadyknollcave.io"

      - name: Checkout repository
        run: |
          git clone https://x-access-token:${{ secrets.GIT_TOKEN }}@git.shadyknollcave.io/micro/tinybird.git /workspace/tinybird
          cd /workspace/tinybird
          git checkout ${{ github.ref_name }}

      - name: Set image tags
        id: tags
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            VERSION="${{ github.ref_name }}"
            echo "tag=${VERSION}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            echo "tag=main-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

      - name: Update Kustomize image tags
        run: |
          cd /workspace/tinybird/k8s/overlays/prod

          # Backup original
          cp kustomization.yaml kustomization.yaml.bak

          # Update images section
          cat > images-patch.yaml <<-EOF
          images:
            - name: tinybirdco/tinybird-local
              newName: ${{ env.TINYBIRD_IMAGE }}
              newTag: latest
            - name: ghost/traffic-analytics
              newName: ${{ env.ANALYTICS_IMAGE }}
              newTag: ${{ steps.tags.outputs.tag }}
          EOF

          # Merge with existing kustomization
          if ! grep -q "^images:" kustomization.yaml; then
            cat images-patch.yaml >> kustomization.yaml
          else
            # Replace existing images section
            sed -i '/^images:/,/^[a-z]/d' kustomization.yaml
            cat images-patch.yaml >> kustomization.yaml
          fi

          rm images-patch.yaml kustomization.yaml.bak

      - name: Commit and push changes
        run: |
          cd /workspace/tinybird

          if git diff --quiet k8s/overlays/prod/kustomization.yaml; then
            echo "No changes to commit"
            exit 0
          fi

          git add k8s/overlays/prod/kustomization.yaml
          git commit -m "chore: update image tags to ${{ steps.tags.outputs.tag }}

          Updated by Gitea Actions workflow
          Commit: ${{ github.sha }}"

          git push origin ${{ github.ref_name }}

      - name: Trigger ArgoCD sync
        if: success()
        run: |
          echo "Manifest updated. ArgoCD will auto-sync if configured."
          echo "Manual sync: argocd app sync tinybird-analytics"
