name: Mirror Upstream Images

# Mirror upstream images weekly to ensure availability

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

env:
  REGISTRY: git.shadyknollcave.io
  REGISTRY_USER: micro

jobs:
  mirror-images:
    name: Mirror Upstream Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - source: docker.io/tinybirdco/tinybird-local:latest
            target_image: tinybird-local
            target_tag: latest
            name: Tinybird Local
          - source: docker.io/tinybirdco/tinybird-local:beta
            target_image: tinybird-local
            target_tag: beta
            name: Tinybird Local Beta

    steps:
      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman version

      - name: Log in to Gitea Container Registry
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin

      - name: Mirror ${{ matrix.name }}
        run: |
          echo "Pulling ${{ matrix.source }}..."
          podman pull --platform linux/amd64 ${{ matrix.source }}

          TARGET="${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ matrix.target_image }}:${{ matrix.target_tag }}"

          echo "Tagging as $TARGET..."
          podman tag ${{ matrix.source }} $TARGET

          echo "Pushing to registry..."
          podman push $TARGET

          # Also tag with date for tracking
          DATE_TAG=$(date +%Y%m%d)
          DATE_TARGET="${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ matrix.target_image }}:${{ matrix.target_tag }}-${DATE_TAG}"
          podman tag ${{ matrix.source }} $DATE_TARGET
          podman push $DATE_TARGET

          echo "✅ Successfully mirrored ${{ matrix.name }}"

      - name: Report success
        if: success()
        run: |
          echo "✅ All images mirrored successfully"
          echo "Images are now available at:"
          echo "  ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/tinybird-local"
